### ISSUE TITLE
the input type of images

### ISSUE THREAD

**Issue by gaunny** [SFPM/iQMetrix-CT#1]
Hi!
I try this project on matlab.But when I try to upload images,it occurs error.The images end with *.dcm . I don't know how to solve it.
![image](https://user-images.githubusercontent.com/48590551/179176100-b0aaa24a-2ee5-4692-ba05-01ec60a7ec0e.png)

![image](https://user-images.githubusercontent.com/48590551/179175969-9cc10aa8-8e3e-421e-b0f2-0e0f19a5ea97.png)

**Comment by YvesBarbotteau** [comment]
Hi,
Did you select the files or the directory containing the files ? Moreover, compressed dicom file are not supported.
Regards.
Yves.
