### ISSUE TITLE
Phantom config file does not exist or is corrupted

### ISSUE THREAD

**Issue by lammour** [SFPM/iQMetrix-CT#2]
Hello,

I am not able to run the NPS analysis, the software returns an error when I select the phantom config file: "The config phantom file does not exist or is corrupted".

Here are the detailed steps of the bug:
- I open IQmetrix-CT v1.1
- I click on "NPS"
- I click on "Select Phantom Config File"
- I select any existing config file
- I get this error message :
![iqmetrix-ct](https://github.com/SFPM/iQMetrix-CT/assets/4402023/c80d5d46-c452-41c5-8d6b-ff5102bd48bb)

Operating system: Windows 10
Matlab runtime: R2022a update 7

Is this a known issue?

**Comment by SFPM** [comment]
Hello Luis,

I think you don't follow the workflow described in the user manual :)
You've to create your own config file first. 
The phantom config file provided with the soft are generic file that you have to use to create your own config file. You can't use them directly.
